### ISSUE TITLE
unable to load uboot.bin after spl.bin

### ISSUE THREAD

**Issue by alexvnesta** [ballaswag/ingenic-usbboot#3]
Hello, this issue could be due to my naivety, but I am unable to get your tool to boot the modified SPL and UBOOT.bin.

I am thinking this is potentially a power issue, but I would appreciate if you could clarify exactly how you are launching your modified SPL and UBOOT.

Here is what I have.

Hardware:
1) RK3328 SBC with USB male to female connected to K1 micro usb port.
2) 5v USB to TTL plugged into the K1 serial port.
3) The RK3328 board is powered by a 3 amp usb power brick, but I have not verified the power delivery. 
4) The only power going to the K1 board is from the RK3328 board. I do not know what the USB power limits are on this device, but this could potentially be our issue. I am doubtful though, because without this SPL and UBOOT, I am able to power the whole K1 board with normal boot from this usb. I unplugged all other connections from the K1 mainboard as a precaution.

Steps to launch SPL and UBOOT:  
1) Clone your git repo, re-make the usbboot tool by running make clean && make
2) Connected from RK3328 SBC to k1 via `sudo screen /dev/ttyUSB0 115200` - Verify console output from normal boot chatter.
3) Run the following:

Attempt 1:
```
alex@renegade:~/ingenic-usbboot$ sudo ./usbboot --cpu x2000 --addr 0x80100000 --download uboot.bin
alex@renegade:~/ingenic-usbboot$ sudo ./usbboot --cpu x2000 --stage1 spl.bin --start1 0xb2401800
alex@renegade:~/ingenic-usbboot$ sudo ./usbboot --cpu x2000 --start2 0x80100000

Request PROGRAM_START2 failed: -7
```

Attempt 2:
```
alex@renegade:~/ingenic-usbboot$ sudo ./usbboot --cpu x2000 --stage1 spl.bin --start1 0xb2401800
alex@renegade:~/ingenic-usbboot$ sudo ./usbboot --cpu x2000 --stage2 uboot.bin --start2 0x80100000
Request SET_DATA_ADDRESS failed: -7
```

Attempt 3:
```
alex@renegade:~/ingenic-usbboot$ sudo ./usbboot --cpu x2000 --stage1 spl.bin --start1 0xb2401800 --stage2 uboot.bin --start2 0x80100000
Request SET_DATA_ADDRESS failed: -7
```
The only thing that seems to partially work is the stage 1 SPL.bin loading. Giving me the following serial output.

```
U-Boot SPL 2013.07-00032-ga0524e4 (Aug 24 2023 - 10:25:53)
ERROR EPC b2401944
Current Version: V2
CPA_CPAPCR:0c70902d
CPM_CPMPCR:0310086d
CPM_CPEPCR:0310186d
CPM_CPCCR:9a094410
DDR: W97BV6MK_LPDDR2 type is : LPDDR2
DDRP_INNOPHY_CALIB_DELAY_AL:00000051
DDRP_INNOPHY_CALIB_DELAY_AH:00000051
-----ddr_readl(DDRP_INNOPHY_CALIB_DONE): 00000003

U-Boot SPL 2013.07-00032-ga0524e4 (Aug 24 2023 - 10:25:53)
ERROR EPC b2401944
Current Version: V2
CPA_CPAPCR:0c70902d
CPM_CPMPCR:0310086d
CPM_CPEPCR:0310186d
CPM_CPCCR:9a094410
DDR: W97BV6MK_LPDDR2 type is : LPDDR2
DDRP_INNOPHY_CALIB_DELAY_AL:00000051
DDRP_INNOPHY_CALIB_DELAY_AH:00000051
-----ddr_readl(DDRP_INNOPHY_CALIB_DONE): 00000003
```

Sometimes I will randomly get this error on serial output repeating indefinitely after attempting to launch SPL.bin:
```
-----ddr_readl(DDRP_INNOPHY_CALIB_DONE): 00000012
DDRP_INNOPHY_CALIB_DELAY_AL:00000051
DDRP_INNOPHY_CALIB_DELAY_AH:00000051
-----ddr_readl(DDRP_INNOPHY_CALIB_DONE): 00000012
DDRP_INNOPHY_CALIB_DELAY_AL:00000051
DDRP_INNOPHY_CALIB_DELAY_AH:00000051
```

I would greatly appreciate your input here!

It looks like there is some issue with initializing the RAM. Perhaps I am writing to the incorrect address?

Additional note, I was able to successfully dump the kernel partition after:
```
$ sudo ./usbboot --uboot

## dump the kernel partition to file ./kernel.out
$ sudo ./usbboot -o 0x000b00000 -s 0x0000800000 --dump-partition ./kernel.out
```

Thanks!
Alex

**Comment by alexvnesta** [comment]
Update - I am dumb and did not fully read the SPL memory address loading and executing at different addresses - also I now see you specified the proper addresses by default. I think I am making progress. I now have the burner_x2000 prompt.

```
alex@renegade:~/ingenic-usbboot$ sudo ./usbboot --uboot --stage1 spl.bin --stage2 uboot.bin
Transfer failed: -7
```

```
U-Boot SPL 2013.07-00032-ga052DDR: W97BV6MK_LPDDR2 type is : LDDRP_INNOPHY_CALIB_DELAY_AL:00000051
DDRP_INNOPHY_CALIB_DELAY_AH:00000051
4e4 (Aug 24 2023 - 10:25:53)CALIB_DONE): 00000003
ER

U-Boot 2013.07 (Sep 25 2023 e for U-Boot at: 90000000
Reser8000
NAND:  0 MiB
Enter 'CDT' mode.
create CDT index: 0 ~ 6,  index number:7.
MMC:   MSC: 0, MSC: 1, MSC: 2
Using default environment

n:    jz_serial
Out:   jz_serial
Err:   jz_serial
USB_udc_probe
jz_dwc2_udc_v1.1
Hit any key to stop alicy manager register
burner_x2000# cloner->full_size 
```

**Comment by ballaswag** [comment]
If you're on the K1, running 

sudo ./usbboot --uboot

Should get you into the uboot prompt. That's the same as manually specifying stage1 and 2.

On your second post, it looks like you succeeded? You got the x2000_burner prompt. That's their custom burner tool uboot for x2000. What isn't working for you at this point and what's your goal?

**Comment by alexvnesta** [comment]
Thanks for your response - you are correct, this is working.

I am trying to figure out how to expose the k1 micro usb port once linux is fully booted. Currently it is only exposed when the K1 is in boot mode.

I am hoping this will enable us to control the on-board MCUs from a usb-connected SBC (The K1 tandem project on discord)
 
 I could be totally off-base here. 
 
Now that I confirmed we can load a spl and uboot file, I want to build a custom uboot that will expose the micro-usb port. I am not sure if this is possible or if it will allow me to communicate with the microcontrollers on the K1 board, but I am just now beginning to look at the uboot source for this.

If I can get that all sorted, we can look into flashing the custom uboot file.

I realize this is now off-topic though, so I think we can close the issue :)
